[build]
  base = "focal" # Utilise l'image de build Ubuntu 20.04 focal
  publish = "build/web"
  command = "./netlify_build.sh"

[context.production.environment]
  PYTHON_VERSION = "3.8"  # Spécifie la version de Python nécessaire
