// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ6m95U5hSIi8xfqjBmbjRcTUBNdZmn5k',
    appId: '1:133774609701:web:bb62aef10d05bfeb635ecc',
    messagingSenderId: '133774609701',
    projectId: 'vintedia-app',
    authDomain: 'vintedia-app.firebaseapp.com',
    storageBucket: 'vintedia-app.appspot.com',
    measurementId: 'G-MJZXKFM759',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlgPz0JU_4kJHMAUzlAq3lXtM1are2f1Y',
    appId: '1:133774609701:android:36ef4e6d4ffc7907635ecc',
    messagingSenderId: '133774609701',
    projectId: 'vintedia-app',
    storageBucket: 'vintedia-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPvhDpsUce7aiAbwRrm5gKgvEFQl3mG_E',
    appId: '1:133774609701:ios:21015b74c42be461635ecc',
    messagingSenderId: '133774609701',
    projectId: 'vintedia-app',
    storageBucket: 'vintedia-app.appspot.com',
    iosBundleId: 'com.example.clothesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPvhDpsUce7aiAbwRrm5gKgvEFQl3mG_E',
    appId: '1:133774609701:ios:21015b74c42be461635ecc',
    messagingSenderId: '133774609701',
    projectId: 'vintedia-app',
    storageBucket: 'vintedia-app.appspot.com',
    iosBundleId: 'com.example.clothesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ6m95U5hSIi8xfqjBmbjRcTUBNdZmn5k',
    appId: '1:133774609701:web:ae6dde0794bcb062635ecc',
    messagingSenderId: '133774609701',
    projectId: 'vintedia-app',
    authDomain: 'vintedia-app.firebaseapp.com',
    storageBucket: 'vintedia-app.appspot.com',
    measurementId: 'G-PWXE092HZ7',
  );

}